CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    picture VARCHAR(255),
    role VARCHAR(255),
    joined_at TIMESTAMP(6)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    repository_name VARCHAR(255) NOT NULL,
    repository_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    api_key_hash VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at DATE NOT NULL,
    deleted_at DATE,
    CONSTRAINT fk_api_keys_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE github_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_github_connections_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE pr_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id VARCHAR(255) NOT NULL UNIQUE,
    repository_full_name VARCHAR(255) NOT NULL,
    pr_number INT NOT NULL,
    pr_title VARCHAR(512),
    action VARCHAR(32) NOT NULL,
    head_sha VARCHAR(40),
    base_sha VARCHAR(40),
    status VARCHAR(255) NOT NULL,
    summary TEXT,
    findings TEXT,
    github_review_id BIGINT,
    raw_payload TEXT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    project_id BIGINT NOT NULL,
    CONSTRAINT fk_pr_reviews_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_review_id BIGINT NOT NULL,
    content TEXT,
    embedding VECTOR(1536) NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT fk_embeddings_pr_review FOREIGN KEY (pr_review_id) REFERENCES pr_reviews (id) ON DELETE CASCADE
);

CREATE TABLE wehbook_secrets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secret VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    CONSTRAINT fk_webhook_secrets_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);
