CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_review_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT fk_messages_pr_review FOREIGN KEY (pr_review_id) REFERENCES pr_reviews (id) ON DELETE CASCADE
);
